version: 2
updates:
  # - package-ecosystem: pip
  #   directory: '/'
  #   schedule:
  #     interval: 'weekly'
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates once a week
      interval: "weekly"
